#!/usr/bin/env python3
"""mksamples.py — bake samples/*.raw into a single samples.h.

Usage:
    python tools/mksamples.py <sample_dir> <output.h>

Expects one file per mode, 8-bit SIGNED mono raw at 48kHz:

    horses.raw  geese.raw  frogs.raw  rain.raw  meteors.raw

Emits `const signed char <mode>_pcm[]` + `const unsigned <mode>_pcm_len` for
each. A missing file becomes a 1-sample silent stub, so a partial sample set
still builds (that mode just plays nothing in PCM boot).

Converting a wav to the expected format with ffmpeg:
    ffmpeg -i clop.wav -ac 1 -ar 48000 -f s8 samples/horses.raw

Flash budget: 2MB total, ~90KB used by code. At 48kHz 8-bit, 1 second = 48KB,
so keep each sample well under a second — these are one-shot percussive hits.
"""
import os
import sys

MODES = ["horses", "geese", "frogs", "rain", "meteors"]


def emit(name, data):
    lines = [f"const unsigned {name}_pcm_len = {len(data)};",
             f"const signed char {name}_pcm[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        # Raw bytes are unsigned; reinterpret as signed two's complement.
        lines.append("    " + "".join(
            f"{b - 256 if b > 127 else b}," for b in chunk))
    lines.append("};")
    return lines


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    sample_dir, out_path = sys.argv[1], sys.argv[2]

    out = ["// Auto-generated by tools/mksamples.py. Do not edit by hand.",
           "#pragma once", ""]
    total = 0
    for mode in MODES:
        path = os.path.join(sample_dir, f"{mode}.raw")
        if os.path.isfile(path):
            with open(path, "rb") as f:
                data = f.read()
            print(f"  {mode}: {len(data)} bytes")
        else:
            data = b"\x00"
            print(f"  {mode}: missing, emitting silent stub")
        total += len(data)
        out += emit(mode, data)
        out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {out_path}: {total} bytes of PCM "
          f"({total / 48000.0:.2f}s at 48kHz)")


if __name__ == "__main__":
    main()
